### PR TITLE
Chore/create base entity class

### PR DESCRIPTION
**Pull request by dehghani-reza**
chore(main-base-entity): create class MainBaseEntity.java

### CODE REVIEW

**Comment by dehghani-reza** [comment]
[Base Entity class](https://trello.com/c/TJ13aku0/4-base-entity-class)

**Comment by amirfathi37** [comment]
Good job!!!
I have some question.
We have isDeleted field, why do we need to deletDate and deleteBy property?Could not we handle delete business with update property and is deleted?
@dehghani-reza

**Comment by amirfathi37** [comment]
Please tell me about ip in MainBaseEtity.
Especially abut its usage.
And about priority, you consider it as a integer.
Should we determinate priority by number of column?
@dehghani-reza

**Comment by dehghani-reza** [comment]
> Good job!!!
> I have some question.
> We have isDeleted field, why do we need to deletDate and deleteBy property?Could not we handle delete business with update property and is deleted?
> @dehghani-reza 

if  your pov is from programming side, yes the object is updating but if you look at it from business side object is going to be deleted and its consider another action than updating
as matter of fact the softdelete function is seperated from update in service

**Comment by dehghani-reza** [comment]
> Please tell me about ip in MainBaseEtity.
> Especially abut its usage.
> And about priority, you consider it as a integer.
> Should we determinate priority by number of column?
> @dehghani-reza 

for now ip gonna fill with user ip address that create the row and insert data to data base but we can have more business in this field later.
about priority some time there is two object that have same level but one of them is prior to other one this field gonna help us there
its going to help us if we have some complex tree bussiness.

**Comment by amirfathi37** [comment]
Please implement the state field and other changes that we have dealt

**Pull request closed without merging**
